name: Go Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup: 
    name: Setup Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.16', '1.17']

  test:
    runs-on: ubuntu-latest
    needs: setup
    name: Run Test
    steps:
      - uses: actions/checkout@v2
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v ./...
  race:
    runs-on: ubuntu-latest
    needs: setup
    name: Run Test with Race flag
    steps:
      - uses: actions/checkout@v2
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v --race ./...
